name: Create Tag and Upload File

# izzy8799 been here

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
  
      - name: Install dependencies
        run: |
          pip install customtkinter download pillow pyinstaller

      - name: Build
        run: |
          pyinstaller --noconfirm --onefile --console --icon "assets/logo.ico" --clean --add-data "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/customtkinter:customtkinter/" --add-data "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/PIL:PIL/" --add-data "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/tkinter/:tkinter/" --hidden-import "Pillow.libs" main.py
      
      - name: Rename file
        run: |
          rename dist/main.exe dist/WineCraft_Build.exe

      - name: Upload Release
        uses: "diillson/auto-release@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "auto"
          prerelease: true
          title: "Automatic Build Windows"
          files: |
            dist/WineCraft_Build.exe
