name: Create Tag and Upload File Windows

# izzy8799 been here

#on:
#  push:
#    branches:
#      - main

# temporary manual build
on:
    workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
  
      - name: Install dependencies
        run: |
          pip install customtkinter download pillow pyinstaller

      - name: Build
        run: |
          pyinstaller --noconfirm --onefile --console --icon "assets\logo.ico" --clean --add-data "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages\customtkinter;customtkinter\" --add-data "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages\PIL;PIL\" --add-data "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\tkinter\;tkinter\" --hidden-import "Pillow.libs" main.py
      
      - name: Rename file
        run: |
          cd dist
          ren "main.exe" "WineCraft_Build.exe"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(Get-Date -Format 'yyyy-MM-dd-HH-mm')"

      - name: Upload Release
        uses: "diillson/auto-release@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "build_${{ steps.date.outputs.date }}_windows"
          prerelease: true
          title: "Automatic Build Windows"
          files: |
            dist/WineCraft_Build.exe
